# -*- coding: utf-8 -*-
"""Spaceship_titanic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n3lod--1yI0au1fMabRWawwVjkjt6CKc
"""

import pandas as pd
from sklearn.model_selection import cross_val_score,train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score , f1_score
from xgboost import XGBClassifier


train=pd.read_csv("train.csv")
test_init = pd.read_csv("test.csv")
'''
print(train.shape)
print(train.head())
print(train.describe())
print(train.info())
print(train.isnull().sum())
'''
#print(test.isnull().sum())

X=train.drop(["PassengerId","Name","Transported","Cabin"],axis =1)
y=train["Transported"]
test = test_init.drop(["PassengerId","Name","Cabin"],axis =1)
Id = test_init["PassengerId"]


#fillna
#numerical
num_cols = X.select_dtypes(include = "number").columns
num_median = X[num_cols].median()
X[num_cols] = X[num_cols].fillna(num_median)
test[num_cols] = test[num_cols].fillna(num_median)

#categorical
cat_cols = X.select_dtypes(include = ["object","string"]).columns
cat_mode = X[cat_cols].mode().iloc[0]
X[cat_cols] = X[cat_cols].fillna(cat_mode)
test[cat_cols] = test[cat_cols].fillna(cat_mode)

#print(X.isnull().sum())
#print(test.isnull().sum())

#Encoding
len_X=len(X)
full_data = pd.concat([X,test])
full_data = pd.get_dummies(full_data,drop_first = True)
X=full_data[:len_X]
test=full_data[len_X:]
print("Here")

rf = RandomForestClassifier(
    n_jobs = -1,
    n_estimators=500,
    max_depth=5,
    min_samples_leaf=3,
    min_samples_split=5,
    random_state=42
    )

score1 = cross_val_score(rf,X,y,cv=5,scoring="accuracy")
print("score RF: ",score1.mean())

model =XGBClassifier(
    n_jobs = -1,
    n_estimators=500,
    max_depth=5,
    min_child_weight=3,
    random_state=42,
    learning_rate = 0.11
    )

score2=cross_val_score(model,X,y,cv=5,scoring="accuracy")
print("score XGB: ",score2.mean())




model.fit(X,y)
print("trained")
predict = model.predict(test)

Submission = pd.DataFrame(
    {"PassengerId":Id,
     "Transported":predict
        }
    )
Submission.to_csv("submission4.csv",index=False)
print("Done")

"""0.7886829659520206 - 0.112
0.789028587385711 - 0.11
"""